Feat/1 bands between uncertainty lines
Pandora-IsoMemo/plotr pull request #34
Opened 2023-05-09 08:53 UTC by f-lukas

2023-05-09 20:46 UTC, arunge requested changes
Looks almost perfect, just two things, and I would like the opacity a bit less.
Could you please add following changes to:
- show a band per default:

  ![image](https://github.com/Pandora-IsoMemo/plotr/assets/16759098/775c5f87-a387-4b35-a7f6-d68a43918d71)
- to fix a typo that I just noted

  ![image](https://github.com/Pandora-IsoMemo/plotr/assets/16759098/07eaec8d-bf47-4697-a82b-e66719e755a1)

Thanks! :slightly_smiling_face:

2023-05-09 20:46 UTC, arunge commented on R/03-stylePlot.R
> +                     value = 0.5,
```suggestion
                     value = 0.2,
```

2023-05-11 07:05 UTC, f-lukas commented
@arunge good idea to show a band per default. Thanks! Could you please check it again?

2023-05-11 07:26 UTC, arunge approved these changes

2023-05-11 07:27 UTC, merged