Aic bic
Pandora-IsoMemo/plotr pull request #37
Opened 2023-06-12 12:41 UTC by mgross

Introduce new UI tab: AIC + BIC

2023-06-12 12:41 UTC, mgross commented
@arunge : can you have a look it?

2023-06-15 15:53 UTC, arunge requested changes
@mgross When trying to load an online test model (1) the app crashes (2). Can you please check what is going on?

![image](https://github.com/Pandora-IsoMemo/plotr/assets/16759098/02e0203d-ec75-4a24-8613-f4793048445e)

![image](https://github.com/Pandora-IsoMemo/plotr/assets/16759098/a2db72fb-4b86-4650-a398-0911099ef400)

2023-06-27 07:39 UTC, mgross commented
fixed it

2023-06-29 07:31 UTC, arunge requested changes
- [x] I opened a new PR where I extracted the function to create the table and added a test. 
  Please merge [that](https://github.com/Pandora-IsoMemo/plotr/pull/38) first.
- [ ] I have some questions regarding `XX`
  - Is it normal that the values in the table differ that much if variable standard deviation (m1) or no variable standard deviation (ms) is used?
  ![image](https://github.com/Pandora-IsoMemo/plotr/assets/16759098/f6533e11-7c25-4657-bff6-9a6ef7d479b6)

2023-06-29 07:31 UTC, arunge commented on DESCRIPTION
> +Version: 23.06.1.0
```suggestion
Version: 23.06.0
```

2023-06-29 07:31 UTC, arunge commented on R/01-fitModel.R
> +  res$llog <- do.call("cbind", lapply(1:length(ret), function(x) ret[[x]]$llog))
Is it correct to use here `cbind` and not `rbind` like for `$beta` and for `$betaSigma`?

2023-06-29 07:31 UTC, arunge commented on R/01-fitModel.R
> +      (XX %*% betamc[usedsamples[x], ]) * sRe + mRe), 1, var) +
I do not understand this part. What is the difference between `XX` and `XX2`?
Why do you not use `XX2` anymore as you did before? Why the switch to `XX`?

2023-06-29 09:36 UTC, arunge commented
@mgross Please also check and merge this PR first: https://github.com/Pandora-IsoMemo/plotr/pull/39 where I extracted the log likelihood computation.

In general, the code already has a lot of long if/else conditionals and is very hard to read and to understand. Could you please avoid to introduce more conditionals directly into an existing function? Please try to split things and create new functions with meaningful names to add new functionality.

2023-07-26 14:45 UTC, arunge commented
@mgross Maybe this got lost: Could check the questions in:
- https://github.com/Pandora-IsoMemo/plotr/pull/37#pullrequestreview-1504642828
- https://github.com/Pandora-IsoMemo/plotr/pull/37#discussion_r1246184791
- https://github.com/Pandora-IsoMemo/plotr/pull/37#discussion_r1246186319

Afterwards we can continue here. :slightly_smiling_face:

2023-07-31 08:41 UTC, mgross commented on R/01-fitModel.R
> +  res$llog <- do.call("cbind", lapply(1:length(ret), function(x) ret[[x]]$llog))
Yes, this is correct :)

2023-07-31 08:42 UTC, mgross commented on R/01-fitModel.R
> +      (XX %*% betamc[usedsamples[x], ]) * sRe + mRe), 1, var) +
You're right. XX2 is the right matrix to use here, I got confused myself. XX2 is the matrix on the original X-Values, while XX is the matrix on the changed X-Values (if there is uncertainty in X)

2023-07-31 08:50 UTC, mgross commented on R/01-fitModel.R
> +      (XX %*% betamc[usedsamples[x], ]) * sRe + mRe), 1, var) +
This should also fix the large AIC/BIC differences between models with and without uncertainty/standard deviation in X

2023-07-31 08:51 UTC, mgross commented
@arunge:
I answered your questions and fixed one issue

2023-07-31 08:52 UTC, mgross commented on R/01-fitModel.R
> +      (XX %*% betamc[usedsamples[x], ]) * sRe + mRe), 1, var) +
In my tests, all is fine now, AIC and BIC are in that case as you would expect (some differences can and will still occur, especially for smaller data)

2023-08-16 07:16 UTC, arunge approved these changes
Thanks for your comments! No all is more clear.

2023-08-16 07:16 UTC, merged